---
- hosts: localhost
  become: yes
  tasks:
    - name: ipv4
      sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: yes

    - name: sysctl
      command: sysctl -p

    - name: astra
      iptables:
        chain: POSTROUTING
        table: nat
        source: 172.16.4.0/28
        jump: MASQUERADE

    - name: alt
      iptables:
        chain: POSTROUTING
        table: nat
        source: 172.16.5.0/28
        jump: MASQUERADE
                           

